package pacman.test;
import static org.junit.Assert.assertEquals;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import pacman.graphics.PacmanGraphics;

public class PacmanTest {

    
    @Test public void testPacman() {
    	
		PacmanGraphics graphics = new PacmanGraphics();
		graphics.setup();
		
		assertEquals("Initial score",0,graphics.getScore());
		assertEquals("Initial time",0,graphics.getTime());
    }
}
